/*
 * Copyright (c) 2026 Doughnuts Publishing
 * All rights reserved.
 *
 * Author: Doughnuts Publishing
 * Licensed under the MIT License. See LICENSE in project root for license details.
 */

using IBM.Data.Db2;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Text;

namespace Dnp.ScriptRunner
{
    class Db2Executor : IDbExecutor
    {
        private DB2Connection? _conn;
        public void Open(string connectionString) { _conn = new DB2Connection(connectionString); _conn.Open(); }
        public string ExecuteNonQuery(string sql)
        {
            using var cmd = _conn!.CreateCommand(); cmd.CommandText = sql; cmd.CommandTimeout = 1800;
            try { cmd.ExecuteNonQuery(); return "Success"; } catch (Exception ex) { return ex.Message; }
        }
        public string ExecuteUpsertWorkflow(string name, string jsonDefinition, int isProduction, int isActive, int isValid, DateTime createdAt, DateTime updatedAt, int version)
        {
            try
            {
                using var tx = _conn!.BeginTransaction();
                using var cmd = _conn.CreateCommand(); cmd.Transaction = tx; cmd.CommandTimeout = 1800;

                cmd.CommandText = "SELECT COUNT(*) FROM Workflows WHERE Name = @Name";
                var p = cmd.CreateParameter(); p.ParameterName = "@Name"; p.Value = name; cmd.Parameters.Add(p);
                var exists = Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
                cmd.Parameters.Clear();

                if (exists)
                {
                    cmd.CommandText = @"UPDATE Workflows SET JsonDefinition = @JsonDefinition, IsProduction = @IsProduction, IsActive = @IsActive, IsValid = @IsValid, UpdatedAt = @UpdatedAt, Version = @Version WHERE Name = @Name";
                    var pj = cmd.CreateParameter(); pj.ParameterName = "@JsonDefinition"; pj.Value = jsonDefinition; cmd.Parameters.Add(pj);
                    var pp = cmd.CreateParameter(); pp.ParameterName = "@IsProduction"; pp.Value = isProduction; cmd.Parameters.Add(pp);
                    var pa = cmd.CreateParameter(); pa.ParameterName = "@IsActive"; pa.Value = isActive; cmd.Parameters.Add(pa);
                    var pv = cmd.CreateParameter(); pv.ParameterName = "@IsValid"; pv.Value = isValid; cmd.Parameters.Add(pv);
                    var pu = cmd.CreateParameter(); pu.ParameterName = "@UpdatedAt"; pu.Value = updatedAt; cmd.Parameters.Add(pu);
                    var pv2 = cmd.CreateParameter(); pv2.ParameterName = "@Version"; pv2.Value = version; cmd.Parameters.Add(pv2);
                    var pn = cmd.CreateParameter(); pn.ParameterName = "@Name"; pn.Value = name; cmd.Parameters.Add(pn);
                    cmd.ExecuteNonQuery();
                }
                else
                {
                    cmd.CommandText = @"INSERT INTO Workflows (Name, JsonDefinition, IsProduction, IsActive, IsValid, CreatedAt, UpdatedAt, Version) VALUES (@Name, @JsonDefinition, @IsProduction, @IsActive, @IsValid, @CreatedAt, @UpdatedAt, @Version)";
                    var pn = cmd.CreateParameter(); pn.ParameterName = "@Name"; pn.Value = name; cmd.Parameters.Add(pn);
                    var pj = cmd.CreateParameter(); pj.ParameterName = "@JsonDefinition"; pj.Value = jsonDefinition; cmd.Parameters.Add(pj);
                    var pp = cmd.CreateParameter(); pp.ParameterName = "@IsProduction"; pp.Value = isProduction; cmd.Parameters.Add(pp);
                    var pa = cmd.CreateParameter(); pa.ParameterName = "@IsActive"; pa.Value = isActive; cmd.Parameters.Add(pa);
                    var pv = cmd.CreateParameter(); pv.ParameterName = "@IsValid"; pv.Value = isValid; cmd.Parameters.Add(pv);
                    var pc = cmd.CreateParameter(); pc.ParameterName = "@CreatedAt"; pc.Value = createdAt; cmd.Parameters.Add(pc);
                    var pu = cmd.CreateParameter(); pu.ParameterName = "@UpdatedAt"; pu.Value = updatedAt; cmd.Parameters.Add(pu);
                    var pv2 = cmd.CreateParameter(); pv2.ParameterName = "@Version"; pv2.Value = version; cmd.Parameters.Add(pv2);
                    cmd.ExecuteNonQuery();
                }

                tx.Commit();
                return "Success";
            }
            catch (Exception ex) { return ex.Message; }
        }
        public string GenerateSchemaScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Schema create script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            var tables = GetTables();

            var schemas = tables.Select(t => t.Schema).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(s => s).ToList();
            foreach (var schema in schemas)
            {
                sb.AppendLine($"CREATE SCHEMA \"{schema}\";");
            }
            if (schemas.Count > 0) sb.AppendLine();

            foreach (var (schema, table) in tables)
            {
                try
                {
                    sb.AppendLine(BuildCreateTable(schema, table));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate DDL for table {schema}.{table}: {ex.Message}");
                    sb.AppendLine();
                    continue;
                }

                foreach (var stmt in GetKeyConstraintStatements(schema, table))
                {
                    sb.AppendLine(stmt);
                    sb.AppendLine();
                }

                foreach (var stmt in GetForeignKeyStatements(schema, table))
                {
                    sb.AppendLine(stmt);
                    sb.AppendLine();
                }

                foreach (var stmt in GetIndexStatements(schema, table))
                {
                    sb.AppendLine(stmt);
                    sb.AppendLine();
                }
            }

            foreach (var (schema, name, def) in GetViews())
            {
                AppendCatalogDefinition(sb, def, "view", $"{schema}.{name}");
            }

            foreach (var (schema, name, type, def) in GetRoutines())
            {
                AppendCatalogDefinition(sb, def, type == "P" ? "procedure" : "function", $"{schema}.{name}");
            }

            foreach (var (schema, name, def) in GetTriggers())
            {
                AppendCatalogDefinition(sb, def, "trigger", $"{schema}.{name}");
            }

            return sb.ToString();
        }

        private static void AppendCatalogDefinition(StringBuilder sb, string? definition, string objectKind, string qualifiedName)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(definition))
                {
                    sb.AppendLine($"-- No stored DDL text available for {objectKind} {qualifiedName}");
                    sb.AppendLine();
                    return;
                }

                sb.AppendLine(definition.TrimEnd().TrimEnd(';') + ";");
                sb.AppendLine();
            }
            catch (Exception ex)
            {
                sb.AppendLine($"-- Failed to generate DDL for {objectKind} {qualifiedName}: {ex.Message}");
                sb.AppendLine();
            }
        }

        private List<(string Schema, string Name, string? Definition)> GetViews()
        {
            var results = new List<(string, string, string?)>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT VIEWSCHEMA, VIEWNAME, TEXT FROM SYSCAT.VIEWS WHERE VIEWSCHEMA NOT LIKE 'SYS%' ORDER BY VIEWSCHEMA, VIEWNAME";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                results.Add((reader.GetString(0).Trim(), reader.GetString(1).Trim(), reader.IsDBNull(2) ? null : reader.GetString(2)));
            }
            return results;
        }

        private List<(string Schema, string Name, string Type, string? Definition)> GetRoutines()
        {
            var results = new List<(string, string, string, string?)>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT ROUTINESCHEMA, ROUTINENAME, ROUTINETYPE, TEXT
                                 FROM SYSCAT.ROUTINES
                                 WHERE ROUTINESCHEMA NOT LIKE 'SYS%' AND ROUTINETYPE IN ('P','F')
                                 ORDER BY ROUTINESCHEMA, ROUTINENAME";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                results.Add((reader.GetString(0).Trim(), reader.GetString(1).Trim(), reader.GetString(2).Trim(), reader.IsDBNull(3) ? null : reader.GetString(3)));
            }
            return results;
        }

        private List<(string Schema, string Name, string? Definition)> GetTriggers()
        {
            var results = new List<(string, string, string?)>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT TRIGSCHEMA, TRIGNAME, TEXT FROM SYSCAT.TRIGGERS WHERE TRIGSCHEMA NOT LIKE 'SYS%' ORDER BY TRIGSCHEMA, TRIGNAME";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                results.Add((reader.GetString(0).Trim(), reader.GetString(1).Trim(), reader.IsDBNull(2) ? null : reader.GetString(2)));
            }
            return results;
        }

        private static void AddParam(DbCommand cmd, string name, object value)
        {
            var p = cmd.CreateParameter();
            p.ParameterName = name;
            p.Value = value;
            cmd.Parameters.Add(p);
        }

        private List<(string Schema, string Table)> GetTables()
        {
            var tables = new List<(string Schema, string Table)>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT TABSCHEMA, TABNAME FROM SYSCAT.TABLES WHERE TYPE = 'T' AND TABSCHEMA NOT LIKE 'SYS%' ORDER BY TABSCHEMA, TABNAME";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) tables.Add((reader.GetString(0).Trim(), reader.GetString(1).Trim()));
            return tables;
        }

        public string GenerateDataScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Data insert script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            foreach (var (schema, table) in GetTables())
            {
                var quoted = $"\"{schema}\".\"{table}\"";
                try
                {
                    sb.Append(GenerateInsertsForTable(quoted));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate data for table {quoted}: {ex.Message}");
                }
            }

            return sb.ToString();
        }

        private string GenerateInsertsForTable(string quotedTableName)
        {
            var sb = new StringBuilder();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = $"SELECT * FROM {quotedTableName}";
            using var reader = cmd.ExecuteReader();
            var columns = Enumerable.Range(0, reader.FieldCount).Select(i => $"\"{reader.GetName(i)}\"").ToList();
            var rowCount = 0;
            while (reader.Read())
            {
                var values = new List<string>();
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    var val = reader.IsDBNull(i) ? null : reader.GetValue(i);
                    values.Add(Helpers.FormatSqlLiteral(val, SqlLiteralProvider.Db2));
                }
                sb.AppendLine($"INSERT INTO {quotedTableName} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
                rowCount++;
            }
            if (rowCount > 0) sb.AppendLine();
            return sb.ToString();
        }

        private string BuildCreateTable(string schema, string table)
        {
            var columns = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT COLNAME, TYPENAME, LENGTH, SCALE, NULLS, DEFAULT, GENERATED
                                 FROM SYSCAT.COLUMNS
                                 WHERE TABSCHEMA = @schema AND TABNAME = @table
                                 ORDER BY COLNO";
            AddParam(cmd, "@schema", schema);
            AddParam(cmd, "@table", table);
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var colName = reader.GetString(0).Trim();
                var typeName = reader.GetString(1).Trim();
                var length = reader.IsDBNull(2) ? 0 : Convert.ToInt32(reader.GetValue(2));
                var scale = reader.IsDBNull(3) ? 0 : Convert.ToInt32(reader.GetValue(3));
                var nulls = reader.GetString(4).Trim();
                var defaultVal = reader.IsDBNull(5) ? null : reader.GetValue(5).ToString();
                var generated = reader.IsDBNull(6) ? " " : reader.GetString(6).Trim();

                var typeSql = BuildColumnType(typeName, length, scale);
                var line = $"    \"{colName}\" {typeSql}";
                if (nulls == "N") line += " NOT NULL";
                if (generated == "A") line += " GENERATED ALWAYS AS IDENTITY";
                else if (generated == "D") line += " GENERATED BY DEFAULT AS IDENTITY";
                else if (!string.IsNullOrEmpty(defaultVal)) line += $" DEFAULT {defaultVal}";
                columns.Add(line);
            }

            return $"CREATE TABLE \"{schema}\".\"{table}\" (\n{string.Join(",\n", columns)}\n);\n";
        }

        private static string BuildColumnType(string typeName, int length, int scale)
        {
            switch (typeName)
            {
                case "VARCHAR":
                case "CHARACTER":
                case "CHAR":
                case "GRAPHIC":
                case "VARGRAPHIC":
                    return $"{typeName}({length})";
                case "DECIMAL":
                case "NUMERIC":
                    return $"{typeName}({length},{scale})";
                default:
                    return typeName;
            }
        }

        private List<string> GetKeyConstraintStatements(string schema, string table)
        {
            var raw = new List<(string ConstName, string Type, string ColName, int Seq)>();
            using (var cmd = _conn!.CreateCommand())
            {
                cmd.CommandText = @"SELECT tc.CONSTNAME, tc.TYPE, kcu.COLNAME, kcu.COLSEQ
                                     FROM SYSCAT.TABCONST tc
                                     JOIN SYSCAT.KEYCOLUSE kcu ON kcu.CONSTNAME = tc.CONSTNAME AND kcu.TABSCHEMA = tc.TABSCHEMA AND kcu.TABNAME = tc.TABNAME
                                     WHERE tc.TABSCHEMA = @schema AND tc.TABNAME = @table AND tc.TYPE IN ('P','U')
                                     ORDER BY tc.CONSTNAME, kcu.COLSEQ";
                AddParam(cmd, "@schema", schema);
                AddParam(cmd, "@table", table);
                using var reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    raw.Add((reader.GetString(0).Trim(), reader.GetString(1).Trim(), reader.GetString(2).Trim(), Convert.ToInt32(reader.GetValue(3))));
                }
            }

            var results = new List<string>();
            foreach (var group in raw.GroupBy(r => new { r.ConstName, r.Type }))
            {
                var cols = string.Join(", ", group.OrderBy(g => g.Seq).Select(g => $"\"{g.ColName}\""));
                var kind = group.Key.Type == "P" ? "PRIMARY KEY" : "UNIQUE";
                results.Add($"ALTER TABLE \"{schema}\".\"{table}\" ADD CONSTRAINT \"{group.Key.ConstName}\" {kind} ({cols});");
            }
            return results;
        }

        private List<string> GetForeignKeyStatements(string schema, string table)
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT CONSTNAME, REFTABSCHEMA, REFTABNAME, FK_COLNAMES, PK_COLNAMES, DELETERULE, UPDATERULE
                                 FROM SYSCAT.REFERENCES
                                 WHERE TABSCHEMA = @schema AND TABNAME = @table";
            AddParam(cmd, "@schema", schema);
            AddParam(cmd, "@table", table);
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var name = reader.GetString(0).Trim();
                var refSchema = reader.GetString(1).Trim();
                var refTable = reader.GetString(2).Trim();
                var fkCols = string.Join(", ", SplitDb2ColNames(reader.GetString(3)).Select(c => $"\"{c}\""));
                var pkCols = string.Join(", ", SplitDb2ColNames(reader.GetString(4)).Select(c => $"\"{c}\""));
                var deleteAction = MapReferentialAction(reader.IsDBNull(5) ? null : reader.GetString(5));
                var updateAction = MapReferentialAction(reader.IsDBNull(6) ? null : reader.GetString(6));
                results.Add($"ALTER TABLE \"{schema}\".\"{table}\" ADD CONSTRAINT \"{name}\" FOREIGN KEY ({fkCols}) REFERENCES \"{refSchema}\".\"{refTable}\" ({pkCols}) ON DELETE {deleteAction} ON UPDATE {updateAction};");
            }
            return results;
        }

        private static IEnumerable<string> SplitDb2ColNames(string raw)
        {
            return raw.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
        }

        private static string MapReferentialAction(string? code) => code?.Trim() switch
        {
            "C" => "CASCADE",
            "N" => "SET NULL",
            "R" => "RESTRICT",
            _ => "NO ACTION"
        };

        private List<string> GetIndexStatements(string schema, string table)
        {
            var indexList = new List<(string Name, string UniqueRule)>();
            using (var cmd = _conn!.CreateCommand())
            {
                cmd.CommandText = @"SELECT INDNAME, UNIQUERULE FROM SYSCAT.INDEXES WHERE TABSCHEMA = @schema AND TABNAME = @table AND UNIQUERULE <> 'P'";
                AddParam(cmd, "@schema", schema);
                AddParam(cmd, "@table", table);
                using var reader = cmd.ExecuteReader();
                while (reader.Read()) indexList.Add((reader.GetString(0).Trim(), reader.GetString(1).Trim()));
            }

            var results = new List<string>();
            foreach (var (indexName, uniqueRule) in indexList)
            {
                var cols = new List<(string ColName, int Seq)>();
                using (var colCmd = _conn!.CreateCommand())
                {
                    colCmd.CommandText = @"SELECT COLNAME, COLSEQ FROM SYSCAT.INDEXCOLUSE WHERE INDSCHEMA = @schema AND INDNAME = @index ORDER BY ABS(COLSEQ)";
                    AddParam(colCmd, "@schema", schema);
                    AddParam(colCmd, "@index", indexName);
                    using var colReader = colCmd.ExecuteReader();
                    while (colReader.Read())
                    {
                        cols.Add((colReader.GetString(0).Trim(), Convert.ToInt32(colReader.GetValue(1))));
                    }
                }

                var colSql = string.Join(", ", cols.Select(c => $"\"{c.ColName}\"" + (c.Seq < 0 ? " DESC" : "")));
                var uniqueSql = uniqueRule == "U" ? "UNIQUE " : "";
                results.Add($"CREATE {uniqueSql}INDEX \"{indexName}\" ON \"{schema}\".\"{table}\" ({colSql});");
            }
            return results;
        }

        public void Dispose() { try { _conn?.Close(); _conn?.Dispose(); } catch { } }
    }
}
