/*
 * Copyright (c) 2026 Doughnuts Publishing
 * All rights reserved.
 *
 * Author: Doughnuts Publishing
 * Licensed under the MIT License. See LICENSE in project root for license details.
 */

using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dnp.ScriptRunner
{
    class MySqlExecutor : IDbExecutor
    {
        private MySqlConnection? _conn;
        public void Open(string connectionString) { _conn = new MySqlConnection(connectionString); _conn.Open(); }
        public string ExecuteNonQuery(string sql)
        {
            using var cmd = _conn!.CreateCommand(); cmd.CommandText = sql; cmd.CommandTimeout = 1800;
            try { cmd.ExecuteNonQuery(); return "Success"; } catch (Exception ex) { return ex.Message; }
        }
        public string ExecuteUpsertWorkflow(string name, string jsonDefinition, int isProduction, int isActive, int isValid, DateTime createdAt, DateTime updatedAt, int version)
        {
            try
            {
                using var tx = _conn!.BeginTransaction();
                using var cmd = _conn.CreateCommand(); cmd.Transaction = tx; cmd.CommandTimeout = 1800;

                cmd.CommandText = "SELECT COUNT(*) FROM Workflows WHERE Name = @Name";
                cmd.Parameters.Add(new MySqlParameter("@Name", name));
                var exists = Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
                cmd.Parameters.Clear();

                if (exists)
                {
                    cmd.CommandText = @"UPDATE Workflows SET JsonDefinition = @JsonDefinition, IsProduction = @IsProduction, IsActive = @IsActive, IsValid = @IsValid, UpdatedAt = @UpdatedAt, Version = @Version WHERE Name = @Name";
                    cmd.Parameters.Add(new MySqlParameter("@JsonDefinition", jsonDefinition));
                    cmd.Parameters.Add(new MySqlParameter("@IsProduction", isProduction));
                    cmd.Parameters.Add(new MySqlParameter("@IsActive", isActive));
                    cmd.Parameters.Add(new MySqlParameter("@IsValid", isValid));
                    cmd.Parameters.Add(new MySqlParameter("@UpdatedAt", updatedAt));
                    cmd.Parameters.Add(new MySqlParameter("@Version", version));
                    cmd.Parameters.Add(new MySqlParameter("@Name", name));
                    cmd.ExecuteNonQuery();
                }
                else
                {
                    cmd.CommandText = @"INSERT INTO Workflows (Name, JsonDefinition, IsProduction, IsActive, IsValid, CreatedAt, UpdatedAt, Version) VALUES (@Name, @JsonDefinition, @IsProduction, @IsActive, @IsValid, @CreatedAt, @UpdatedAt, @Version)";
                    cmd.Parameters.Add(new MySqlParameter("@Name", name));
                    cmd.Parameters.Add(new MySqlParameter("@JsonDefinition", jsonDefinition));
                    cmd.Parameters.Add(new MySqlParameter("@IsProduction", isProduction));
                    cmd.Parameters.Add(new MySqlParameter("@IsActive", isActive));
                    cmd.Parameters.Add(new MySqlParameter("@IsValid", isValid));
                    cmd.Parameters.Add(new MySqlParameter("@CreatedAt", createdAt));
                    cmd.Parameters.Add(new MySqlParameter("@UpdatedAt", updatedAt));
                    cmd.Parameters.Add(new MySqlParameter("@Version", version));
                    cmd.ExecuteNonQuery();
                }

                tx.Commit();
                return "Success";
            }
            catch (Exception ex) { return ex.Message; }
        }
        public string GenerateSchemaScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Schema create script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            using (var cmd = _conn!.CreateCommand())
            {
                cmd.CommandText = "SELECT DATABASE()";
                var dbName = cmd.ExecuteScalar() as string;
                if (!string.IsNullOrEmpty(dbName))
                {
                    sb.AppendLine($"CREATE SCHEMA IF NOT EXISTS `{dbName}`;");
                    sb.AppendLine($"USE `{dbName}`;");
                    sb.AppendLine();
                }
            }

            foreach (var table in GetTables())
            {
                try
                {
                    using var cmd = _conn!.CreateCommand();
                    cmd.CommandText = $"SHOW CREATE TABLE `{table.Replace("`", "``")}`";
                    using var reader = cmd.ExecuteReader();
                    if (reader.Read())
                    {
                        var createStatement = reader.GetString(1);
                        sb.AppendLine(createStatement + ";");
                        sb.AppendLine();
                    }
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate DDL for table `{table}`: {ex.Message}");
                    sb.AppendLine();
                }
            }

            AppendShowCreateObjects(sb, GetViewNames(), "VIEW", 1);
            AppendShowCreateObjects(sb, GetRoutineNames("PROCEDURE"), "PROCEDURE", 2);
            AppendShowCreateObjects(sb, GetRoutineNames("FUNCTION"), "FUNCTION", 2);
            AppendShowCreateObjects(sb, GetTriggerNames(), "TRIGGER", 2);

            return sb.ToString();
        }

        private void AppendShowCreateObjects(StringBuilder sb, IEnumerable<string> names, string objectKeyword, int definitionColumnIndex)
        {
            foreach (var name in names)
            {
                try
                {
                    using var cmd = _conn!.CreateCommand();
                    cmd.CommandText = $"SHOW CREATE {objectKeyword} `{name.Replace("`", "``")}`";
                    using var reader = cmd.ExecuteReader();
                    if (reader.Read())
                    {
                        sb.AppendLine(reader.GetString(definitionColumnIndex) + ";");
                        sb.AppendLine();
                    }
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate DDL for {objectKeyword.ToLowerInvariant()} `{name}`: {ex.Message}");
                    sb.AppendLine();
                }
            }
        }

        private List<string> GetViewNames()
        {
            var names = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT table_name FROM information_schema.tables WHERE table_schema = DATABASE() AND table_type = 'VIEW' ORDER BY table_name";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) names.Add(reader.GetString(0));
            return names;
        }

        private List<string> GetRoutineNames(string routineType)
        {
            var names = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT routine_name FROM information_schema.routines WHERE routine_schema = DATABASE() AND routine_type = @type ORDER BY routine_name";
            cmd.Parameters.Add(new MySqlParameter("@type", routineType));
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) names.Add(reader.GetString(0));
            return names;
        }

        private List<string> GetTriggerNames()
        {
            var names = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT trigger_name FROM information_schema.triggers WHERE trigger_schema = DATABASE() ORDER BY trigger_name";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) names.Add(reader.GetString(0));
            return names;
        }

        private List<string> GetTables()
        {
            var tables = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT table_name FROM information_schema.tables WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE' ORDER BY table_name";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) tables.Add(reader.GetString(0));
            return tables;
        }

        public string GenerateDataScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Data insert script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            foreach (var table in GetTables())
            {
                var quoted = $"`{table.Replace("`", "``")}`";
                try
                {
                    sb.Append(GenerateInsertsForTable(quoted));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate data for table `{table}`: {ex.Message}");
                }
            }

            return sb.ToString();
        }

        private string GenerateInsertsForTable(string quotedTableName)
        {
            var sb = new StringBuilder();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = $"SELECT * FROM {quotedTableName}";
            using var reader = cmd.ExecuteReader();
            var columns = Enumerable.Range(0, reader.FieldCount).Select(i => $"`{reader.GetName(i).Replace("`", "``")}`").ToList();
            var rowCount = 0;
            while (reader.Read())
            {
                var values = new List<string>();
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    var val = reader.IsDBNull(i) ? null : reader.GetValue(i);
                    values.Add(Helpers.FormatSqlLiteral(val));
                }
                sb.AppendLine($"INSERT INTO {quotedTableName} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
                rowCount++;
            }
            if (rowCount > 0) sb.AppendLine();
            return sb.ToString();
        }

        public void Dispose() { try { _conn?.Close(); _conn?.Dispose(); } catch { } }
    }
}
