/*
 * Copyright (c) 2026 Doughnuts Publishing
 * All rights reserved.
 *
 * Author: Doughnuts Publishing
 * Licensed under the MIT License. See LICENSE in project root for license details.
 */

using Oracle.ManagedDataAccess.Client;
using Oracle.ManagedDataAccess.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dnp.ScriptRunner
{
    class OracleExecutor : IDbExecutor
    {
        private OracleConnection? _conn;
        public void Open(string connectionString) { _conn = new OracleConnection(connectionString); _conn.Open(); }
        public string ExecuteNonQuery(string sql)
        {
            using var cmd = _conn!.CreateCommand(); cmd.CommandText = sql; cmd.CommandTimeout = 1800;
            try { cmd.ExecuteNonQuery(); return "Success"; } catch (Exception ex) { return ex.Message; }
        }
        public string ExecuteUpsertWorkflow(string name, string jsonDefinition, int isProduction, int isActive, int isValid, DateTime createdAt, DateTime updatedAt, int version)
        {
            try
            {
                using var tx = _conn!.BeginTransaction();
                using var cmd = _conn.CreateCommand(); cmd.Transaction = tx; cmd.CommandTimeout = 1800;

                cmd.CommandText = "SELECT COUNT(*) FROM Workflows WHERE Name = :Name";
                cmd.Parameters.Add(new OracleParameter(":Name", name));
                var exists = Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
                cmd.Parameters.Clear();

                if (exists)
                {
                    cmd.CommandText = @"UPDATE Workflows SET JsonDefinition = :JsonDefinition, IsProduction = :IsProduction, IsActive = :IsActive, IsValid = :IsValid, UpdatedAt = :UpdatedAt, Version = :Version WHERE Name = :Name";
                    cmd.Parameters.Add(new OracleParameter(":JsonDefinition", jsonDefinition));
                    cmd.Parameters.Add(new OracleParameter(":IsProduction", isProduction));
                    cmd.Parameters.Add(new OracleParameter(":IsActive", isActive));
                    cmd.Parameters.Add(new OracleParameter(":IsValid", isValid));
                    cmd.Parameters.Add(new OracleParameter(":UpdatedAt", updatedAt));
                    cmd.Parameters.Add(new OracleParameter(":Version", version));
                    cmd.Parameters.Add(new OracleParameter(":Name", name));
                    cmd.ExecuteNonQuery();
                }
                else
                {
                    cmd.CommandText = @"INSERT INTO Workflows (Name, JsonDefinition, IsProduction, IsActive, IsValid, CreatedAt, UpdatedAt, Version) VALUES (:Name, :JsonDefinition, :IsProduction, :IsActive, :IsValid, :CreatedAt, :UpdatedAt, :Version)";
                    cmd.Parameters.Add(new OracleParameter(":Name", name));
                    cmd.Parameters.Add(new OracleParameter(":JsonDefinition", jsonDefinition));
                    cmd.Parameters.Add(new OracleParameter(":IsProduction", isProduction));
                    cmd.Parameters.Add(new OracleParameter(":IsActive", isActive));
                    cmd.Parameters.Add(new OracleParameter(":IsValid", isValid));
                    cmd.Parameters.Add(new OracleParameter(":CreatedAt", createdAt));
                    cmd.Parameters.Add(new OracleParameter(":UpdatedAt", updatedAt));
                    cmd.Parameters.Add(new OracleParameter(":Version", version));
                    cmd.ExecuteNonQuery();
                }

                tx.Commit();
                return "Success";
            }
            catch (Exception ex) { return ex.Message; }
        }
        public string GenerateSchemaScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Schema create script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            // Suppress storage/tablespace noise so the DDL is more portable
            using (var settingsCmd = _conn!.CreateCommand())
            {
                settingsCmd.CommandText = "BEGIN DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE); DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE); END;";
                try { settingsCmd.ExecuteNonQuery(); } catch { }
            }

            var tables = GetTables();

            foreach (var table in tables)
            {
                try
                {
                    using var cmd = _conn!.CreateCommand();
                    cmd.CommandText = "SELECT DBMS_METADATA.GET_DDL('TABLE', :t) FROM dual";
                    cmd.Parameters.Add(new OracleParameter(":t", table));
                    var ddl = ReadClobResult(cmd.ExecuteScalar());
                    if (!string.IsNullOrWhiteSpace(ddl))
                    {
                        sb.AppendLine(ddl.TrimEnd().TrimEnd(';') + ";");
                        sb.AppendLine();
                    }
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate DDL for table {table}: {ex.Message}");
                    sb.AppendLine();
                    continue;
                }

                // Standalone indexes not already produced as part of a constraint on this table
                var indexes = new List<string>();
                try
                {
                    using var idxCmd = _conn!.CreateCommand();
                    idxCmd.CommandText = @"SELECT index_name FROM user_indexes WHERE table_name = :t
                                            AND index_name NOT IN (SELECT constraint_name FROM user_constraints WHERE table_name = :t AND constraint_name IS NOT NULL)
                                            ORDER BY index_name";
                    idxCmd.Parameters.Add(new OracleParameter(":t", table));
                    using var idxReader = idxCmd.ExecuteReader();
                    while (idxReader.Read()) indexes.Add(idxReader.GetString(0));
                }
                catch { }

                foreach (var idx in indexes)
                {
                    try
                    {
                        using var idxDdlCmd = _conn!.CreateCommand();
                        idxDdlCmd.CommandText = "SELECT DBMS_METADATA.GET_DDL('INDEX', :i) FROM dual";
                        idxDdlCmd.Parameters.Add(new OracleParameter(":i", idx));
                        var idxDdl = ReadClobResult(idxDdlCmd.ExecuteScalar());
                        if (!string.IsNullOrWhiteSpace(idxDdl))
                        {
                            sb.AppendLine(idxDdl.TrimEnd().TrimEnd(';') + ";");
                            sb.AppendLine();
                        }
                    }
                    catch (Exception ex)
                    {
                        sb.AppendLine($"-- Failed to generate DDL for index {idx}: {ex.Message}");
                        sb.AppendLine();
                    }
                }
            }

            foreach (var (name, type) in GetObjectsByType("VIEW", "FUNCTION", "PROCEDURE", "TRIGGER"))
            {
                try
                {
                    using var cmd = _conn!.CreateCommand();
                    cmd.CommandText = "SELECT DBMS_METADATA.GET_DDL(:type, :name) FROM dual";
                    cmd.Parameters.Add(new OracleParameter(":type", type));
                    cmd.Parameters.Add(new OracleParameter(":name", name));
                    var ddl = ReadClobResult(cmd.ExecuteScalar());
                    if (!string.IsNullOrWhiteSpace(ddl))
                    {
                        sb.AppendLine(ddl.TrimEnd().TrimEnd(';') + ";");
                        sb.AppendLine();
                    }
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate DDL for {type} {name}: {ex.Message}");
                    sb.AppendLine();
                }
            }

            return sb.ToString();
        }

        private List<(string Name, string Type)> GetObjectsByType(params string[] types)
        {
            var results = new List<(string Name, string Type)>();
            using var cmd = _conn!.CreateCommand();
            var placeholders = string.Join(",", types.Select((_, idx) => $":t{idx}"));
            cmd.CommandText = $"SELECT object_name, object_type FROM user_objects WHERE object_type IN ({placeholders}) AND status = 'VALID' ORDER BY object_type, object_name";
            for (var i = 0; i < types.Length; i++) cmd.Parameters.Add(new OracleParameter($":t{i}", types[i]));
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) results.Add((reader.GetString(0), reader.GetString(1)));
            return results;
        }

        private static string ReadClobResult(object? result)
        {
            return result switch
            {
                null or DBNull => string.Empty,
                string s => s,
                OracleClob clob => clob.Value,
                _ => result.ToString() ?? string.Empty
            };
        }

        private List<string> GetTables()
        {
            var tables = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT table_name FROM user_tables ORDER BY table_name";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) tables.Add(reader.GetString(0));
            return tables;
        }

        public string GenerateDataScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Data insert script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            foreach (var table in GetTables())
            {
                var quoted = $"\"{table}\"";
                try
                {
                    sb.Append(GenerateInsertsForTable(quoted));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate data for table {table}: {ex.Message}");
                }
            }

            return sb.ToString();
        }

        private string GenerateInsertsForTable(string quotedTableName)
        {
            var sb = new StringBuilder();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = $"SELECT * FROM {quotedTableName}";
            using var reader = cmd.ExecuteReader();
            var columns = Enumerable.Range(0, reader.FieldCount).Select(i => $"\"{reader.GetName(i)}\"").ToList();
            var rowCount = 0;
            while (reader.Read())
            {
                var values = new List<string>();
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    var raw = reader.IsDBNull(i) ? null : reader.GetValue(i);
                    values.Add(Helpers.FormatSqlLiteral(NormalizeOracleValue(raw), SqlLiteralProvider.Oracle));
                }
                sb.AppendLine($"INSERT INTO {quotedTableName} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
                rowCount++;
            }
            if (rowCount > 0) sb.AppendLine();
            return sb.ToString();
        }

        private static object? NormalizeOracleValue(object? value)
        {
            return value switch
            {
                null or DBNull => null,
                OracleClob clob => clob.Value,
                OracleBlob blob => blob.Value,
                _ => value
            };
        }

        public void Dispose() { try { _conn?.Close(); _conn?.Dispose(); } catch { } }
    }
}
