/*
 * Copyright (c) 2026 Doughnuts Publishing
 * All rights reserved.
 *
 * Author: Doughnuts Publishing
 * Licensed under the MIT License. See LICENSE in project root for license details.
 */

using Npgsql;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dnp.ScriptRunner
{
    class PostgresExecutor : IDbExecutor
    {
        private NpgsqlConnection? _conn;
        public void Open(string connectionString) { _conn = new NpgsqlConnection(connectionString); _conn.Open(); }
        public string ExecuteNonQuery(string sql)
        {
            using var cmd = _conn!.CreateCommand(); cmd.CommandText = sql; cmd.CommandTimeout = 1800;
            try { cmd.ExecuteNonQuery(); return "Success"; } catch (Exception ex) { return ex.Message; }
        }
        public string ExecuteUpsertWorkflow(string name, string jsonDefinition, int isProduction, int isActive, int isValid, DateTime createdAt, DateTime updatedAt, int version)
        {
            try
            {
                using var tx = _conn!.BeginTransaction();
                using var cmd = _conn.CreateCommand(); cmd.Transaction = tx; cmd.CommandTimeout = 1800;

                cmd.CommandText = "SELECT COUNT(*) FROM Workflows WHERE Name = @Name";
                cmd.Parameters.Add(new NpgsqlParameter("@Name", NpgsqlTypes.NpgsqlDbType.Text) { Value = name });
                var exists = Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
                cmd.Parameters.Clear();

                if (exists)
                {
                    cmd.CommandText = @"UPDATE Workflows SET JsonDefinition = @JsonDefinition, IsProduction = @IsProduction, IsActive = @IsActive, IsValid = @IsValid, UpdatedAt = @UpdatedAt, Version = @Version WHERE Name = @Name";
                    cmd.Parameters.Add(new NpgsqlParameter("@JsonDefinition", NpgsqlTypes.NpgsqlDbType.Jsonb) { Value = jsonDefinition });
                    cmd.Parameters.Add(new NpgsqlParameter("@IsProduction", NpgsqlTypes.NpgsqlDbType.Integer) { Value = isProduction });
                    cmd.Parameters.Add(new NpgsqlParameter("@IsActive", NpgsqlTypes.NpgsqlDbType.Integer) { Value = isActive });
                    cmd.Parameters.Add(new NpgsqlParameter("@IsValid", NpgsqlTypes.NpgsqlDbType.Integer) { Value = isValid });
                    cmd.Parameters.Add(new NpgsqlParameter("@UpdatedAt", NpgsqlTypes.NpgsqlDbType.Timestamp) { Value = updatedAt });
                    cmd.Parameters.Add(new NpgsqlParameter("@Version", NpgsqlTypes.NpgsqlDbType.Integer) { Value = version });
                    cmd.Parameters.Add(new NpgsqlParameter("@Name", NpgsqlTypes.NpgsqlDbType.Text) { Value = name });
                    cmd.ExecuteNonQuery();
                }
                else
                {
                    cmd.CommandText = @"INSERT INTO Workflows (Name, JsonDefinition, IsProduction, IsActive, IsValid, CreatedAt, UpdatedAt, Version) VALUES (@Name, @JsonDefinition, @IsProduction, @IsActive, @IsValid, @CreatedAt, @UpdatedAt, @Version)";
                    cmd.Parameters.Add(new NpgsqlParameter("@Name", NpgsqlTypes.NpgsqlDbType.Text) { Value = name });
                    cmd.Parameters.Add(new NpgsqlParameter("@JsonDefinition", NpgsqlTypes.NpgsqlDbType.Jsonb) { Value = jsonDefinition });
                    cmd.Parameters.Add(new NpgsqlParameter("@IsProduction", NpgsqlTypes.NpgsqlDbType.Integer) { Value = isProduction });
                    cmd.Parameters.Add(new NpgsqlParameter("@IsActive", NpgsqlTypes.NpgsqlDbType.Integer) { Value = isActive });
                    cmd.Parameters.Add(new NpgsqlParameter("@IsValid", NpgsqlTypes.NpgsqlDbType.Integer) { Value = isValid });
                    cmd.Parameters.Add(new NpgsqlParameter("@CreatedAt", NpgsqlTypes.NpgsqlDbType.Timestamp) { Value = createdAt });
                    cmd.Parameters.Add(new NpgsqlParameter("@UpdatedAt", NpgsqlTypes.NpgsqlDbType.Timestamp) { Value = updatedAt });
                    cmd.Parameters.Add(new NpgsqlParameter("@Version", NpgsqlTypes.NpgsqlDbType.Integer) { Value = version });
                    cmd.ExecuteNonQuery();
                }

                tx.Commit();
                return "Success";
            }
            catch (Exception ex) { return ex.Message; }
        }
        public string GenerateSchemaScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Schema create script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            var tables = GetTables();

            var schemas = tables.Select(t => t.Schema).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(s => s).ToList();
            foreach (var schema in schemas)
            {
                sb.AppendLine($"CREATE SCHEMA IF NOT EXISTS \"{schema}\";");
            }
            if (schemas.Count > 0) sb.AppendLine();

            foreach (var (schema, table) in tables)
            {
                try
                {
                    sb.AppendLine(BuildCreateTable(schema, table));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate DDL for table {schema}.{table}: {ex.Message}");
                    sb.AppendLine();
                    continue;
                }

                foreach (var constraintDef in GetConstraintStatements(schema, table))
                {
                    sb.AppendLine(constraintDef);
                    sb.AppendLine();
                }

                foreach (var indexDef in GetIndexStatements(schema, table))
                {
                    sb.AppendLine(indexDef);
                    sb.AppendLine();
                }
            }

            try
            {
                foreach (var viewDef in GetViewStatements())
                {
                    sb.AppendLine(viewDef);
                    sb.AppendLine();
                }
            }
            catch (Exception ex)
            {
                sb.AppendLine($"-- Failed to generate view DDL: {ex.Message}");
                sb.AppendLine();
            }

            try
            {
                foreach (var funcDef in GetFunctionStatements())
                {
                    sb.AppendLine(funcDef);
                    sb.AppendLine();
                }
            }
            catch (Exception ex)
            {
                sb.AppendLine($"-- Failed to generate function/procedure DDL: {ex.Message}");
                sb.AppendLine();
            }

            try
            {
                foreach (var trigDef in GetTriggerStatements())
                {
                    sb.AppendLine(trigDef);
                    sb.AppendLine();
                }
            }
            catch (Exception ex)
            {
                sb.AppendLine($"-- Failed to generate trigger DDL: {ex.Message}");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        private List<string> GetViewStatements()
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT n.nspname, c.relname, pg_get_viewdef(c.oid, true)
                                 FROM pg_class c
                                 JOIN pg_namespace n ON n.oid = c.relnamespace
                                 WHERE c.relkind = 'v'
                                 AND n.nspname NOT IN ('pg_catalog','information_schema')
                                 ORDER BY n.nspname, c.relname";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var schema = reader.GetString(0);
                var name = reader.GetString(1);
                var def = reader.GetString(2).TrimEnd().TrimEnd(';');
                results.Add($"CREATE OR REPLACE VIEW \"{schema}\".\"{name}\" AS\n{def};");
            }
            return results;
        }

        private List<string> GetFunctionStatements()
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT pg_get_functiondef(p.oid)
                                 FROM pg_proc p
                                 JOIN pg_namespace n ON n.oid = p.pronamespace
                                 WHERE n.nspname NOT IN ('pg_catalog','information_schema')
                                 AND p.prokind IN ('f','p')
                                 ORDER BY n.nspname, p.proname";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var def = reader.GetString(0).TrimEnd().TrimEnd(';');
                results.Add(def + ";");
            }
            return results;
        }

        private List<string> GetTriggerStatements()
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT pg_get_triggerdef(t.oid, true)
                                 FROM pg_trigger t
                                 JOIN pg_class c ON c.oid = t.tgrelid
                                 JOIN pg_namespace n ON n.oid = c.relnamespace
                                 WHERE NOT t.tgisinternal
                                 AND n.nspname NOT IN ('pg_catalog','information_schema')
                                 ORDER BY n.nspname, c.relname, t.tgname";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var def = reader.GetString(0).TrimEnd().TrimEnd(';');
                results.Add(def + ";");
            }
            return results;
        }

        private List<(string Schema, string Table)> GetTables()
        {
            var tables = new List<(string Schema, string Table)>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT n.nspname, c.relname
                                 FROM pg_class c
                                 JOIN pg_namespace n ON n.oid = c.relnamespace
                                 WHERE c.relkind = 'r'
                                 AND n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')
                                 ORDER BY n.nspname, c.relname";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) tables.Add((reader.GetString(0), reader.GetString(1)));
            return tables;
        }

        public string GenerateDataScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Data insert script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            foreach (var (schema, table) in GetTables())
            {
                var quoted = $"\"{schema}\".\"{table}\"";
                try
                {
                    sb.Append(GenerateInsertsForTable(quoted));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate data for table {schema}.{table}: {ex.Message}");
                }
            }

            return sb.ToString();
        }

        private string GenerateInsertsForTable(string quotedTableName)
        {
            var sb = new StringBuilder();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = $"SELECT * FROM {quotedTableName}";
            using var reader = cmd.ExecuteReader();
            var columns = Enumerable.Range(0, reader.FieldCount).Select(i => $"\"{reader.GetName(i)}\"").ToList();
            var rowCount = 0;
            while (reader.Read())
            {
                var values = new List<string>();
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    var val = reader.IsDBNull(i) ? null : reader.GetValue(i);
                    values.Add(Helpers.FormatSqlLiteral(val, SqlLiteralProvider.Postgres));
                }
                sb.AppendLine($"INSERT INTO {quotedTableName} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
                rowCount++;
            }
            if (rowCount > 0) sb.AppendLine();
            return sb.ToString();
        }

        private string BuildCreateTable(string schema, string table)
        {
            var columns = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT column_name, data_type, udt_name, character_maximum_length, numeric_precision, numeric_scale, is_nullable, column_default
                                 FROM information_schema.columns
                                 WHERE table_schema = @schema AND table_name = @table
                                 ORDER BY ordinal_position";
            cmd.Parameters.Add(new NpgsqlParameter("@schema", schema));
            cmd.Parameters.Add(new NpgsqlParameter("@table", table));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var columnName = reader.GetString(0);
                var dataType = reader.GetString(1);
                var udtName = reader.GetString(2);
                int? charMaxLen = reader.IsDBNull(3) ? null : reader.GetInt32(3);
                int? numPrecision = reader.IsDBNull(4) ? null : reader.GetInt32(4);
                int? numScale = reader.IsDBNull(5) ? null : reader.GetInt32(5);
                var isNullable = reader.GetString(6);
                var columnDefault = reader.IsDBNull(7) ? null : reader.GetString(7);

                var typeSql = BuildColumnType(dataType, udtName, charMaxLen, numPrecision, numScale);
                var line = $"    \"{columnName}\" {typeSql}";
                if (isNullable == "NO") line += " NOT NULL";
                if (!string.IsNullOrEmpty(columnDefault)) line += $" DEFAULT {columnDefault}";
                columns.Add(line);
            }

            return $"CREATE TABLE \"{schema}\".\"{table}\" (\n{string.Join(",\n", columns)}\n);\n";
        }

        private static string BuildColumnType(string dataType, string udtName, int? charMaxLen, int? numPrecision, int? numScale)
        {
            if (dataType == "ARRAY")
            {
                var baseType = udtName.StartsWith("_") ? udtName.Substring(1) : udtName;
                return $"{baseType}[]";
            }

            switch (dataType)
            {
                case "character varying":
                    return charMaxLen.HasValue ? $"varchar({charMaxLen})" : "varchar";
                case "character":
                    return charMaxLen.HasValue ? $"char({charMaxLen})" : "char";
                case "numeric":
                    if (numPrecision.HasValue && numScale.HasValue) return $"numeric({numPrecision},{numScale})";
                    if (numPrecision.HasValue) return $"numeric({numPrecision})";
                    return "numeric";
                default:
                    return dataType;
            }
        }

        private List<string> GetConstraintStatements(string schema, string table)
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT con.conname, pg_get_constraintdef(con.oid)
                                 FROM pg_constraint con
                                 JOIN pg_class t ON t.oid = con.conrelid
                                 JOIN pg_namespace n ON n.oid = t.relnamespace
                                 WHERE n.nspname = @schema AND t.relname = @table
                                 ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 WHEN 'c' THEN 3 ELSE 4 END, con.conname";
            cmd.Parameters.Add(new NpgsqlParameter("@schema", schema));
            cmd.Parameters.Add(new NpgsqlParameter("@table", table));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var name = reader.GetString(0);
                var def = reader.GetString(1);
                results.Add($"ALTER TABLE \"{schema}\".\"{table}\" ADD CONSTRAINT \"{name}\" {def};");
            }
            return results;
        }

        private List<string> GetIndexStatements(string schema, string table)
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT i.indexname, i.indexdef
                                 FROM pg_indexes i
                                 WHERE i.schemaname = @schema AND i.tablename = @table
                                 AND i.indexname NOT IN (
                                     SELECT con.conname FROM pg_constraint con
                                     JOIN pg_class t ON t.oid = con.conrelid
                                     JOIN pg_namespace n ON n.oid = t.relnamespace
                                     WHERE n.nspname = @schema AND t.relname = @table
                                 )
                                 ORDER BY i.indexname";
            cmd.Parameters.Add(new NpgsqlParameter("@schema", schema));
            cmd.Parameters.Add(new NpgsqlParameter("@table", table));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                results.Add(reader.GetString(1) + ";");
            }
            return results;
        }

        public void Dispose() { try { _conn?.Close(); _conn?.Dispose(); } catch { } }
    }
}
