/*
 * Copyright (c) 2026 Doughnuts Publishing
 * All rights reserved.
 *
 * Author: Doughnuts Publishing
 * Licensed under the MIT License. See LICENSE in project root for license details.
 */

using Microsoft.Data.Sqlite;
using System;
using System.Linq;
using System.Text;

namespace Dnp.ScriptRunner
{
    class SqliteExecutor : IDbExecutor
    {
        private SqliteConnection? _conn;

        public void Open(string connectionString)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));

            // If the input looks like a raw file path (no '='), build a proper connection string
            if (!connectionString.Contains('='))
            {
                var builder = new SqliteConnectionStringBuilder { DataSource = connectionString };
                connectionString = builder.ToString();
            }

            _conn = new SqliteConnection(connectionString);
            _conn.Open();
        }

        public string ExecuteNonQuery(string sql)
        {
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = sql;
            cmd.CommandTimeout = 1800;
            try { cmd.ExecuteNonQuery(); return "Success"; } catch (Exception ex) { return ex.Message; }
        }

        public string ExecuteUpsertWorkflow(string name, string jsonDefinition, int isProduction, int isActive, int isValid, DateTime createdAt, DateTime updatedAt, int version)
        {
            try
            {
                using var tx = _conn!.BeginTransaction();
                using var cmd = _conn.CreateCommand(); cmd.Transaction = tx; cmd.CommandTimeout = 1800;

                cmd.CommandText = "SELECT COUNT(*) FROM Workflows WHERE Name = @Name";
                cmd.Parameters.Add(new SqliteParameter("@Name", name));
                var exists = Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
                cmd.Parameters.Clear();

                if (exists)
                {
                    cmd.CommandText = @"UPDATE Workflows SET JsonDefinition = @JsonDefinition, IsProduction = @IsProduction, IsActive = @IsActive, IsValid = @IsValid, UpdatedAt = @UpdatedAt, Version = @Version WHERE Name = @Name";
                    cmd.Parameters.Add(new SqliteParameter("@JsonDefinition", jsonDefinition));
                    cmd.Parameters.Add(new SqliteParameter("@IsProduction", isProduction));
                    cmd.Parameters.Add(new SqliteParameter("@IsActive", isActive));
                    cmd.Parameters.Add(new SqliteParameter("@IsValid", isValid));
                    cmd.Parameters.Add(new SqliteParameter("@UpdatedAt", updatedAt));
                    cmd.Parameters.Add(new SqliteParameter("@Version", version));
                    cmd.Parameters.Add(new SqliteParameter("@Name", name));
                    cmd.ExecuteNonQuery();
                }
                else
                {
                    cmd.CommandText = @"INSERT INTO Workflows (Name, JsonDefinition, IsProduction, IsActive, IsValid, CreatedAt, UpdatedAt, Version) VALUES (@Name, @JsonDefinition, @IsProduction, @IsActive, @IsValid, @CreatedAt, @UpdatedAt, @Version)";
                    cmd.Parameters.Add(new SqliteParameter("@Name", name));
                    cmd.Parameters.Add(new SqliteParameter("@JsonDefinition", jsonDefinition));
                    cmd.Parameters.Add(new SqliteParameter("@IsProduction", isProduction));
                    cmd.Parameters.Add(new SqliteParameter("@IsActive", isActive));
                    cmd.Parameters.Add(new SqliteParameter("@IsValid", isValid));
                    cmd.Parameters.Add(new SqliteParameter("@CreatedAt", createdAt));
                    cmd.Parameters.Add(new SqliteParameter("@UpdatedAt", updatedAt));
                    cmd.Parameters.Add(new SqliteParameter("@Version", version));
                    cmd.ExecuteNonQuery();
                }

                tx.Commit();
                return "Success";
            }
            catch (Exception ex) { return ex.Message; }
        }

        public string GenerateSchemaScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Schema create script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT sql FROM sqlite_master
                                 WHERE type IN ('table','index','view','trigger')
                                 AND name NOT LIKE 'sqlite_%'
                                 AND sql IS NOT NULL
                                 ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 1 WHEN 'index' THEN 2 WHEN 'trigger' THEN 3 ELSE 4 END, name";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var sql = reader.GetString(0);
                sb.AppendLine(sql.TrimEnd().TrimEnd(';') + ";");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        public string GenerateDataScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Data insert script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            foreach (var table in GetTables())
            {
                var quoted = $"\"{table}\"";
                try
                {
                    sb.Append(GenerateInsertsForTable(quoted));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate data for table {table}: {ex.Message}");
                }
            }

            return sb.ToString();
        }

        private List<string> GetTables()
        {
            var tables = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) tables.Add(reader.GetString(0));
            return tables;
        }

        private string GenerateInsertsForTable(string quotedTableName)
        {
            var sb = new StringBuilder();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = $"SELECT * FROM {quotedTableName}";
            using var reader = cmd.ExecuteReader();
            var columns = Enumerable.Range(0, reader.FieldCount).Select(i => $"\"{reader.GetName(i)}\"").ToList();
            var rowCount = 0;
            while (reader.Read())
            {
                var values = new List<string>();
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    var val = reader.IsDBNull(i) ? null : reader.GetValue(i);
                    values.Add(Helpers.FormatSqlLiteral(val));
                }
                sb.AppendLine($"INSERT INTO {quotedTableName} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
                rowCount++;
            }
            if (rowCount > 0) sb.AppendLine();
            return sb.ToString();
        }

        public void Dispose() { try { _conn?.Close(); _conn?.Dispose(); } catch { } }
    }
}
