/*
 * Copyright (c) 2026 Doughnuts Publishing
 * All rights reserved.
 *
 * Author: Doughnuts Publishing
 * Licensed under the MIT License. See LICENSE in project root for license details.
 */

using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace Dnp.ScriptRunner
{
    class SqlServerExecutor : IDbExecutor
    {
        private SqlConnection? _conn;
        public void Open(string connectionString) { _conn = new SqlConnection(connectionString); _conn.Open(); }
        public string ExecuteNonQuery(string sql)
        {
            using var cmd = _conn!.CreateCommand(); cmd.CommandText = sql; cmd.CommandTimeout = 1800;
            try { cmd.ExecuteNonQuery(); return "Success"; } catch (Exception ex) { return ex.Message; }
        }

        public string ExecuteUpsertWorkflow(string name, string jsonDefinition, int isProduction, int isActive, int isValid, DateTime createdAt, DateTime updatedAt, int version)
        {
            try
            {
                using var tx = _conn!.BeginTransaction();
                using var cmd = _conn.CreateCommand(); cmd.Transaction = tx; cmd.CommandTimeout = 1800;

                cmd.CommandText = "SELECT COUNT(*) FROM Workflows WHERE Name = @Name";
                cmd.Parameters.Add(new SqlParameter("@Name", SqlDbType.NVarChar) { Value = name });
                var exists = Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
                cmd.Parameters.Clear();

                if (exists)
                {
                    cmd.CommandText = @"UPDATE Workflows SET JsonDefinition = @JsonDefinition, IsProduction = @IsProduction, IsActive = @IsActive, IsValid = @IsValid, UpdatedAt = @UpdatedAt, Version = @Version WHERE Name = @Name";
                    cmd.Parameters.Add(new SqlParameter("@JsonDefinition", SqlDbType.NVarChar) { Value = jsonDefinition });
                    cmd.Parameters.Add(new SqlParameter("@IsProduction", SqlDbType.Int) { Value = isProduction });
                    cmd.Parameters.Add(new SqlParameter("@IsActive", SqlDbType.Int) { Value = isActive });
                    cmd.Parameters.Add(new SqlParameter("@IsValid", SqlDbType.Int) { Value = isValid });
                    cmd.Parameters.Add(new SqlParameter("@UpdatedAt", SqlDbType.DateTime2) { Value = updatedAt });
                    cmd.Parameters.Add(new SqlParameter("@Version", SqlDbType.Int) { Value = version });
                    cmd.Parameters.Add(new SqlParameter("@Name", SqlDbType.NVarChar) { Value = name });
                    cmd.ExecuteNonQuery();
                }
                else
                {
                    cmd.CommandText = @"INSERT INTO Workflows (Name, JsonDefinition, IsProduction, IsActive, IsValid, CreatedAt, UpdatedAt, Version) VALUES (@Name, @JsonDefinition, @IsProduction, @IsActive, @IsValid, @CreatedAt, @UpdatedAt, @Version)";
                    cmd.Parameters.Add(new SqlParameter("@Name", SqlDbType.NVarChar) { Value = name });
                    cmd.Parameters.Add(new SqlParameter("@JsonDefinition", SqlDbType.NVarChar) { Value = jsonDefinition });
                    cmd.Parameters.Add(new SqlParameter("@IsProduction", SqlDbType.Int) { Value = isProduction });
                    cmd.Parameters.Add(new SqlParameter("@IsActive", SqlDbType.Int) { Value = isActive });
                    cmd.Parameters.Add(new SqlParameter("@IsValid", SqlDbType.Int) { Value = isValid });
                    cmd.Parameters.Add(new SqlParameter("@CreatedAt", SqlDbType.DateTime2) { Value = createdAt });
                    cmd.Parameters.Add(new SqlParameter("@UpdatedAt", SqlDbType.DateTime2) { Value = updatedAt });
                    cmd.Parameters.Add(new SqlParameter("@Version", SqlDbType.Int) { Value = version });
                    cmd.ExecuteNonQuery();
                }

                tx.Commit();
                return "Success";
            }
            catch (Exception ex) { return ex.Message; }
        }

        public string GenerateSchemaScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Schema create script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            var tables = GetTables();

            var schemas = tables.Select(t => t.Schema)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .Where(s => !s.Equals("dbo", StringComparison.OrdinalIgnoreCase))
                .OrderBy(s => s)
                .ToList();
            foreach (var schema in schemas)
            {
                sb.AppendLine($"IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'{schema.Replace("'", "''")}')");
                sb.AppendLine($"EXEC('CREATE SCHEMA [{schema}]');");
                sb.AppendLine();
            }

            foreach (var (schema, table) in tables)
            {
                var fullName = $"[{schema}].[{table}]";
                try
                {
                    sb.AppendLine(BuildCreateTable(schema, table, fullName));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate DDL for table {fullName}: {ex.Message}");
                    sb.AppendLine();
                    continue;
                }

                foreach (var stmt in GetKeyConstraintStatements(schema, table, fullName))
                {
                    sb.AppendLine(stmt);
                    sb.AppendLine();
                }

                foreach (var stmt in GetForeignKeyStatements(schema, table, fullName))
                {
                    sb.AppendLine(stmt);
                    sb.AppendLine();
                }

                foreach (var stmt in GetIndexStatements(schema, table, fullName))
                {
                    sb.AppendLine(stmt);
                    sb.AppendLine();
                }
            }

            try
            {
                // Views, functions, procedures and triggers must each be the only statement in their batch,
                // so separate them with GO (recognized both by sqlcmd/SSMS and this tool's own batch splitter)
                foreach (var stmt in GetModuleStatements())
                {
                    sb.AppendLine(stmt);
                    sb.AppendLine("GO");
                    sb.AppendLine();
                }
            }
            catch (Exception ex)
            {
                sb.AppendLine($"-- Failed to generate view/function/procedure/trigger DDL: {ex.Message}");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        private List<string> GetModuleStatements()
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT o.type, m.definition
                                 FROM sys.sql_modules m
                                 JOIN sys.objects o ON o.object_id = m.object_id
                                 JOIN sys.schemas s ON s.schema_id = o.schema_id
                                 WHERE o.type IN ('V','FN','IF','TF','P','TR')
                                 AND m.definition IS NOT NULL
                                 ORDER BY CASE o.type WHEN 'V' THEN 0 WHEN 'FN' THEN 1 WHEN 'IF' THEN 1 WHEN 'TF' THEN 1 WHEN 'P' THEN 2 WHEN 'TR' THEN 3 ELSE 4 END, s.name, o.name";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                results.Add(reader.GetString(1).TrimEnd());
            }
            return results;
        }

        private List<(string Schema, string Table)> GetTables()
        {
            var tables = new List<(string Schema, string Table)>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = "SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_SCHEMA, TABLE_NAME";
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) tables.Add((reader.GetString(0), reader.GetString(1)));
            return tables;
        }

        public string GenerateDataScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Data insert script generated by ScriptRunner");
            sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            foreach (var (schema, table) in GetTables())
            {
                var quoted = $"[{schema}].[{table}]";
                var hasIdentity = TableHasIdentityColumn(schema, table);
                if (hasIdentity) sb.AppendLine($"SET IDENTITY_INSERT {quoted} ON;");

                try
                {
                    sb.Append(GenerateInsertsForTable(quoted));
                }
                catch (Exception ex)
                {
                    sb.AppendLine($"-- Failed to generate data for table {quoted}: {ex.Message}");
                }

                if (hasIdentity) sb.AppendLine($"SET IDENTITY_INSERT {quoted} OFF;");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        private bool TableHasIdentityColumn(string schema, string table)
        {
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT COUNT(*) FROM sys.identity_columns ic
                                 JOIN sys.tables t ON t.object_id = ic.object_id
                                 JOIN sys.schemas s ON s.schema_id = t.schema_id
                                 WHERE s.name = @schema AND t.name = @table";
            cmd.Parameters.Add(new SqlParameter("@schema", schema));
            cmd.Parameters.Add(new SqlParameter("@table", table));
            return Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
        }

        private string GenerateInsertsForTable(string quotedTableName)
        {
            var sb = new StringBuilder();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = $"SELECT * FROM {quotedTableName}";
            using var reader = cmd.ExecuteReader();
            var columns = Enumerable.Range(0, reader.FieldCount).Select(i => $"[{reader.GetName(i)}]").ToList();
            var rowCount = 0;
            while (reader.Read())
            {
                var values = new List<string>();
                for (var i = 0; i < reader.FieldCount; i++)
                {
                    var val = reader.IsDBNull(i) ? null : reader.GetValue(i);
                    values.Add(Helpers.FormatSqlLiteral(val));
                }
                sb.AppendLine($"INSERT INTO {quotedTableName} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
                rowCount++;
            }
            if (rowCount > 0) sb.AppendLine();
            return sb.ToString();
        }

        private string BuildCreateTable(string schema, string table, string fullName)
        {
            var columns = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT c.name, ty.name, c.max_length, c.precision, c.scale, c.is_nullable, c.is_identity, ic.seed_value, ic.increment_value, dc.definition
                                 FROM sys.columns c
                                 JOIN sys.types ty ON ty.user_type_id = c.user_type_id
                                 LEFT JOIN sys.identity_columns ic ON ic.object_id = c.object_id AND ic.column_id = c.column_id
                                 LEFT JOIN sys.default_constraints dc ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
                                 WHERE c.object_id = OBJECT_ID(@fullName)
                                 ORDER BY c.column_id";
            cmd.Parameters.Add(new SqlParameter("@fullName", fullName));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var colName = reader.GetString(0);
                var typeName = reader.GetString(1);
                var maxLength = reader.GetInt16(2);
                var precision = reader.GetByte(3);
                var scale = reader.GetByte(4);
                var isNullable = reader.GetBoolean(5);
                var isIdentity = reader.GetBoolean(6);
                long? seed = reader.IsDBNull(7) ? null : Convert.ToInt64(reader.GetValue(7));
                long? increment = reader.IsDBNull(8) ? null : Convert.ToInt64(reader.GetValue(8));
                var defaultDef = reader.IsDBNull(9) ? null : reader.GetString(9);

                var typeSql = BuildColumnType(typeName, maxLength, precision, scale);
                var line = $"    [{colName}] {typeSql}";
                if (isIdentity) line += $" IDENTITY({seed ?? 1},{increment ?? 1})";
                line += isNullable ? " NULL" : " NOT NULL";
                if (!string.IsNullOrEmpty(defaultDef)) line += $" DEFAULT {defaultDef}";
                columns.Add(line);
            }

            return $"CREATE TABLE [{schema}].[{table}] (\n{string.Join(",\n", columns)}\n);\n";
        }

        private static string BuildColumnType(string typeName, short maxLength, byte precision, byte scale)
        {
            switch (typeName)
            {
                case "varchar":
                case "char":
                case "varbinary":
                case "binary":
                    return maxLength == -1 ? $"{typeName}(MAX)" : $"{typeName}({maxLength})";
                case "nvarchar":
                case "nchar":
                    return maxLength == -1 ? $"{typeName}(MAX)" : $"{typeName}({maxLength / 2})";
                case "decimal":
                case "numeric":
                    return $"{typeName}({precision},{scale})";
                default:
                    return typeName;
            }
        }

        private List<string> GetKeyConstraintStatements(string schema, string table, string fullName)
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT kc.name, kc.type,
                                        STRING_AGG(QUOTENAME(col.name), ', ') WITHIN GROUP (ORDER BY ic.key_ordinal)
                                 FROM sys.key_constraints kc
                                 JOIN sys.indexes i ON i.object_id = kc.parent_object_id AND i.index_id = kc.unique_index_id
                                 JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
                                 JOIN sys.columns col ON col.object_id = ic.object_id AND col.column_id = ic.column_id
                                 WHERE kc.parent_object_id = OBJECT_ID(@fullName)
                                 GROUP BY kc.name, kc.type";
            cmd.Parameters.Add(new SqlParameter("@fullName", fullName));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var name = reader.GetString(0);
                var type = reader.GetString(1);
                var cols = reader.GetString(2);
                var kind = type == "PK" ? "PRIMARY KEY" : "UNIQUE";
                results.Add($"ALTER TABLE [{schema}].[{table}] ADD CONSTRAINT [{name}] {kind} ({cols});");
            }
            return results;
        }

        private List<string> GetForeignKeyStatements(string schema, string table, string fullName)
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT fk.name,
                                        OBJECT_SCHEMA_NAME(fk.referenced_object_id), OBJECT_NAME(fk.referenced_object_id),
                                        STRING_AGG(QUOTENAME(pc.name), ', ') WITHIN GROUP (ORDER BY fkc.constraint_column_id),
                                        STRING_AGG(QUOTENAME(rc.name), ', ') WITHIN GROUP (ORDER BY fkc.constraint_column_id),
                                        fk.delete_referential_action_desc, fk.update_referential_action_desc
                                 FROM sys.foreign_keys fk
                                 JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
                                 JOIN sys.columns pc ON pc.object_id = fkc.parent_object_id AND pc.column_id = fkc.parent_column_id
                                 JOIN sys.columns rc ON rc.object_id = fkc.referenced_object_id AND rc.column_id = fkc.referenced_column_id
                                 WHERE fk.parent_object_id = OBJECT_ID(@fullName)
                                 GROUP BY fk.name, fk.referenced_object_id, fk.delete_referential_action_desc, fk.update_referential_action_desc";
            cmd.Parameters.Add(new SqlParameter("@fullName", fullName));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var name = reader.GetString(0);
                var refSchema = reader.GetString(1);
                var refTable = reader.GetString(2);
                var parentCols = reader.GetString(3);
                var refCols = reader.GetString(4);
                var deleteAction = MapReferentialAction(reader.GetString(5));
                var updateAction = MapReferentialAction(reader.GetString(6));
                results.Add($"ALTER TABLE [{schema}].[{table}] ADD CONSTRAINT [{name}] FOREIGN KEY ({parentCols}) REFERENCES [{refSchema}].[{refTable}] ({refCols}) ON DELETE {deleteAction} ON UPDATE {updateAction};");
            }
            return results;
        }

        private static string MapReferentialAction(string desc) => desc switch
        {
            "CASCADE" => "CASCADE",
            "SET_NULL" => "SET NULL",
            "SET_DEFAULT" => "SET DEFAULT",
            _ => "NO ACTION"
        };

        private List<string> GetIndexStatements(string schema, string table, string fullName)
        {
            var results = new List<string>();
            using var cmd = _conn!.CreateCommand();
            cmd.CommandText = @"SELECT i.name, i.is_unique,
                                        STRING_AGG(QUOTENAME(c.name) + CASE WHEN ic.is_descending_key = 1 THEN ' DESC' ELSE ' ASC' END, ', ') WITHIN GROUP (ORDER BY ic.key_ordinal)
                                 FROM sys.indexes i
                                 JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id AND ic.is_included_column = 0
                                 JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
                                 WHERE i.object_id = OBJECT_ID(@fullName) AND i.is_primary_key = 0 AND i.is_unique_constraint = 0 AND i.type > 0
                                 GROUP BY i.name, i.is_unique";
            cmd.Parameters.Add(new SqlParameter("@fullName", fullName));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var name = reader.GetString(0);
                var isUnique = reader.GetBoolean(1);
                var cols = reader.GetString(2);
                var uniqueSql = isUnique ? "UNIQUE " : "";
                results.Add($"CREATE {uniqueSql}INDEX [{name}] ON [{schema}].[{table}] ({cols});");
            }
            return results;
        }

        public void Dispose() { try { _conn?.Close(); _conn?.Dispose(); } catch { } }
    }
}
