-- Oracle: create schema (user) and table if missing
-- Note: Creating an entire Oracle database is an administrative task and typically
-- cannot be done with a simple SQL script against an existing instance.
-- Instead, create a tablespace and user (schema) using DBA privileges, then
-- run the table creation below as that user.
--
-- Example (run as a DBA / SYSDBA):
-- CREATE TABLESPACE WORLD_DATA DATAFILE '/u01/app/oracle/oradata/WORLD/world_data01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M;
-- CREATE USER world IDENTIFIED BY "YourStrongPassword" DEFAULT TABLESPACE WORLD_DATA QUOTA UNLIMITED ON WORLD_DATA;
-- GRANT CONNECT, RESOURCE TO world;
--
-- After creating the user/schema, connect as that user and run the table create.
-- The block below will create the WORLD.COUNTRIES table if it does not already exist.

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO cnt
    FROM all_tables
    WHERE owner = 'WORLD' AND table_name = 'COUNTRIES';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE WORLD.COUNTRIES (
                Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                Name VARCHAR2(200) NOT NULL,
                Capital VARCHAR2(200) NOT NULL,
                Languages CLOB NULL,
                Population NUMBER(19) NOT NULL
            )
        ';
    END IF;
END;
